# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_base_item', models.CharField(max_length=255)),
                ('order_style', models.CharField(max_length=255)),
                ('order_logo', models.ImageField(blank=True, upload_to=b'')),
                ('order_item_placement', models.CharField(max_length=255)),
                ('order_logo_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_logo_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_details', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_details', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
