# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='created',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='extra_details',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='order_base_item',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='order_item_placement',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='order_logo',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='order_logo_height',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='order_logo_width',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='order_style',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='total',
        ),
    ]
