# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_delete_shoppingcart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='order_number',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='placed_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.PlacedOrder'),
        ),
    ]
