# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20171107_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='placed_order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
