# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_delete_shoppingcart'),
        ('cart', '0005_auto_20171107_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Order')),
                ('placed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.PlacedOrder')),
            ],
        ),
    ]
