# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20171107_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
