# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_placedorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
