# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20171107_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
