# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20171108_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
