# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_hat_jacket_shirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='hat',
            name='style',
        ),
        migrations.RemoveField(
            model_name='jacket',
            name='style',
        ),
        migrations.DeleteModel(
            name='Hat',
        ),
        migrations.DeleteModel(
            name='Jacket',
        ),
    ]
