# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20170927_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='style',
        ),
        migrations.AddField(
            model_name='hatstyle',
            name='base_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='builder.BaseItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jacketstyle',
            name='base_item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='builder.BaseItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirtstyle',
            name='base_item',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='builder.BaseItem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
