# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_style_base_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.BaseItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='hatstyle',
            name='base_item',
        ),
        migrations.RemoveField(
            model_name='jacketstyle',
            name='base_item',
        ),
        migrations.RemoveField(
            model_name='shirtstyle',
            name='base_item',
        ),
        migrations.DeleteModel(
            name='HatStyle',
        ),
        migrations.DeleteModel(
            name='JacketStyle',
        ),
        migrations.DeleteModel(
            name='ShirtStyle',
        ),
    ]
