# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_auto_20170927_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.BaseItem')),
            ],
        ),
    ]
