# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_base_item', models.CharField(max_length=255)),
                ('order_style', models.CharField(max_length=255)),
                ('order_logo', models.ImageField(blank=True, upload_to=b'')),
                ('order_item_placement', models.CharField(max_length=255)),
                ('order_logo_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_logo_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item_color', models.CharField(max_length=255)),
                ('order_item_size', models.CharField(max_length=255)),
                ('order_item_quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
            ],
        ),
    ]
