# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_order_orderitem_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_details',
            field=models.TextField(blank=True),
        ),
    ]
