# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_auto_20171016_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_logo',
            field=models.ImageField(blank=True, upload_to='orders/%m/%d/%Y'),
        ),
    ]
