# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_order_extra_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_details',
            field=models.TextField(blank=True, default='No Specifications Included'),
        ),
    ]
