# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_auto_20171107_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
