# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_delete_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logo_colors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
